#!/bin/bash

make "do_fits" || exit 1

n_threads="8"

#----------------------------------------------------------------------------------------------------

function ProcessOne()
{
	local buffer="$1"

	for d in $buffer
	do
		#echo "    $d"
		./do_fits "$d" &> "$d/do_fits.log"
		if [ $? -ne 0 ]
		then
			echo "ERROR: run problem in $d"
		fi
	done
}

#----------------------------------------------------------------------------------------------------

# collect data
idx=0
input=()
for dir in data/fill_*/run_*/alignment_*
do
	if [ -f "$dir/output.root" ]
	then
		input[$idx]="${input[$idx]} $dir"
		idx=$(( (idx+1) % n_threads ))
	else
		echo "ERROR: no output.root in $dir"
	fi
done

# run in parallel
for (( idx=0; idx<n_threads; idx++))
do
	ProcessOne "${input[$idx]}" &
done
