#!/bin/bash

function RunOne()
{
	local cfgFile="${1}_cfg.py"
	local logFile="${1}.log"

	cat "$cfgFile" | sed "\
			s|\$events|$events|;\
		" > "$dir/$cfgFile"

	cd "$dir"

	#cmsRun "$cfgFile" &> "$logFile" &

	cd - &> /dev/null
}


#----------------------------------------------------------------------------------------------------

function Run()
{
	events="$1"
	dir="$2"

	rm -rf "$dir"
	mkdir "$dir"

	cp "base_cff.py" "$dir"

	#RunOne test_low_th_level1
	#RunOne test_low_th_level2
	#RunOne test_low_th_level3
	#RunOne test_low_th_level4
	
	RunOne test_large_th_level1
	RunOne test_large_th_level2
	RunOne test_large_th_level3
	RunOne test_large_th_level4
}

#----------------------------------------------------------------------------------------------------

Run "100" "1E2"
